export const mockCodev = {
  id: '1',
  first_name: 'John',
  last_name: 'Doe',
  internal_status: 'AVAILABLE',
  main_position: 'Senior Developer',
  projects: [{ id: 'p1', name: 'Project A' }, { id: 'p2', name: 'Project B' }],
  nda_status: 'Signed',
  email: 'john.doe@example.com',
  user_id: 'u1',
  image_url: 'https://example.com/avatar.jpg',
  address: '123 Main St',
  about: 'Experienced developer',
  contact: '123-456-7890',
  education: 'BS Computer Science',
  socials: { linkedin: 'https://linkedin.com/johndoe' },
  tech_stacks: ['React', 'Node.js'],
  job_status: 'Active',
  portfolio_website: 'https://johndoe.dev',
  user: {} as any,
};