import { Codev } from "@/types/home/codev";

export const mockCodevData: Codev[] = [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    internal_status: "AVAILABLE",
    main_position: "Senior Developer",
    projects: [
      { id: "p1", name: "Project A" },
      { id: "p2", name: "Project B" },
    ],
    nda_status: "Signed",
    email: "john.doe@example.com",
    user_id: "u1",
    image_url: "https://example.com/avatar.jpg",
    address: "123 Main St",
    about: "Experienced developer",
    contact: "123-456-7890",
    education: "BS Computer Science",
    socials: { linkedin: "https://linkedin.com/johndoe" },
    tech_stacks: ["React", "Node.js"],
    job_status: "Active",
    portfolio_website: "https://johndoe.dev",
    user: {} as any, // Simplified for this example
  },
  {
    id: "2",
    first_name: "Jane",
    last_name: "Smith",
    internal_status: "DEPLOYED",
    main_position: "Frontend Developer",
    projects: [
      { id: "p3", name: "E-Commerce Platform" },
      { id: "p4", name: "Mobile App" },
    ],
    nda_status: "Signed",
    email: "jane.smith@example.com",
    user_id: "u2",
    image_url: "https://example.com/avatar2.jpg",
    address: "456 Oak Avenue",
    about: "Specialized in building responsive interfaces.",
    contact: "987-654-3210",
    education: "BA Information Technology",
    socials: { github: "https://github.com/janesmith" },
    tech_stacks: ["Vue.js", "TailwindCSS"],
    job_status: "Active",
    portfolio_website: "https://janesmith.dev",
    user: {} as any,
  },
  {
    id: "3",
    first_name: "Michael",
    last_name: "Johnson",
    internal_status: "TRAINING",
    main_position: "Backend Developer",
    projects: [
      { id: "p5", name: "API Development" },
      { id: "p6", name: "Data Analysis Tool" },
    ],
    nda_status: "Pending",
    email: "michael.johnson@example.com",
    user_id: "u3",
    image_url: "https://example.com/avatar3.jpg",
    address: "789 Pine Street",
    about: "Passionate about scalable backend solutions.",
    contact: "456-789-0123",
    education: "MS Software Engineering",
    socials: { twitter: "https://twitter.com/michaeljohnson" },
    tech_stacks: ["Python", "Django", "PostgreSQL"],
    job_status: "Active",
    portfolio_website: "https://michaeljohnson.dev",
    user: {} as any,
  },
  {
    id: "4",
    first_name: "Emily",
    last_name: "Davis",
    internal_status: "BUSY",
    main_position: "Full Stack Developer",
    projects: [
      { id: "p7", name: "CRM System" },
      { id: "p8", name: "Analytics Dashboard" },
    ],
    nda_status: "Signed",
    email: "emily.davis@example.com",
    user_id: "u4",
    image_url: "https://example.com/avatar4.jpg",
    address: "101 Maple Blvd",
    about: "Expert in delivering end-to-end solutions.",
    contact: "321-654-0987",
    education: "BS Computer Engineering",
    socials: { linkedin: "https://linkedin.com/emilydavis" },
    tech_stacks: ["Angular", "Node.js", "MongoDB"],
    job_status: "Active",
    portfolio_website: "https://emilydavis.dev",
    user: {} as any,
  },
];
