import { Codev } from "@/types/home/codev";

export const mockCodev: Codev[] = [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    internal_status: "AVAILABLE",
    main_position: "Senior Developer",
    projects: [
      { id: "p1", name: "Project A" },
      { id: "p2", name: "Project B" },
    ],
    nda_status: "Signed",
    email: "john.doe@example.com",
    user_id: "u1",
    image_url: "https://example.com/avatar.jpg",
    address: "123 Main St",
    about: "Experienced developer",
    contact: "123-456-7890",
    education: "BS Computer Science",
    socials: { linkedin: "https://linkedin.com/johndoe" },
    tech_stacks: ["React", "Node.js"],
    job_status: "Active",
    portfolio_website: "https://johndoe.dev",
    user: {} as any,
  },
  {
    id: "2",
    first_name: "Jane",
    last_name: "Doe",
    internal_status: "AVAILABLE",
    main_position: "Senior Developer",
    projects: [
      { id: "p1", name: "Project A" },
      { id: "p2", name: "Project B" },
    ],
    nda_status: "Signed",
    email: "jane.doe@example.com",
    user_id: "u1",
    image_url: "https://example.com/avatar.jpg",
    address: "123 Main St",
    about: "Experienced developer",
    contact: "123-456-7890",
    education: "BS Computer Science",
    socials: { linkedin: "https://linkedin.com/janedoe" },
    tech_stacks: ["React", "Node.js"],
    job_status: "Active",
    portfolio_website: "https://janedoe.dev",
    user: {} as any,
  },
  {
    id: "3",
    first_name: "Alice",
    last_name: "Smith",
    internal_status: "BUSY",
    main_position: "Project Manager",
    projects: [
      { id: "p3", name: "Project C" },
      { id: "p4", name: "Project D" },
    ],
    nda_status: "Pending",
    email: "alice.smith@example.com",
    user_id: "u2",
    image_url: "https://example.com/avatar2.jpg",
    address: "456 Elm St",
    about: "Skilled project manager",
    contact: "987-654-3210",
    education: "MBA",
    socials: { linkedin: "https://linkedin.com/alicesmith" },
    tech_stacks: ["Agile", "Scrum"],
    job_status: "Active",
    portfolio_website: "https://alicesmith.dev",
    user: {} as any,
  },
  {
    id: "4",
    first_name: "Bob",
    last_name: "Johnson",
    internal_status: "TRAINING",
    main_position: "Junior Developer",
    projects: [
      { id: "p5", name: "Project E" },
      { id: "p6", name: "Project F" },
    ],
    nda_status: "Signed",
    email: "bob.johnson@example.com",
    user_id: "u3",
    image_url: "https://example.com/avatar3.jpg",
    address: "789 Pine St",
    about: "Enthusiastic junior developer",
    contact: "555-123-4567",
    education: "BS Software Engineering",
    socials: { linkedin: "https://linkedin.com/bobjohnson" },
    tech_stacks: ["JavaScript", "Python"],
    job_status: "Active",
    portfolio_website: "https://bobjohnson.dev",
    user: {} as any,
  },
];
