export const INTERNAL_STATUS = {
  AVAILABLE: "AVAILABLE",
  DEPLOYED: "DEPLOYED",
  TRAINING: "TRAINING",
  VACATION: "VACATION",
  BUSY: "BUSY",
  CLIENT_READY: "CLIENTREADY",
  GRADUATED: "GRADUATED",
  FAILED: "FAILED",
};
