import {
  IconAngular,
  IconAWS,
  IconBootstrap,
  IconC,
  IconCPlusPlus,
  IconCSharp,
  IconCSS,
  IconDjango,
  IconFigma,
  IconFirebase,
  IconHTML,
  IconJava,
  IconJavaScript,
  IconJQuery,
  IconKotlin,
  IconMongoDB,
  IconMySQL,
  IconNextJS,
  IconNodeJS,
  IconPHP,
  IconPostgreSQL,
  IconPython,
  IconReact,
  IconReactNative,
  IconRuby,
  IconSolidity,
  IconSwift,
  IconTailwind,
  IconTypeScript,
  IconVue,
} from "@/public/assets/svgs";

export const techstacks = [
  { name: "Angular", icon: IconAngular },
  { name: "AWS", icon: IconAWS },
  { name: "Bootstrap", icon: IconBootstrap },
  { name: "C", icon: IconC },
  { name: "C++", alias: "cplus-plus", icon: IconCPlusPlus },
  { name: "CSharp", icon: IconCSharp },
  { name: "CSS", icon: IconCSS },
  { name: "Django", icon: IconDjango },
  { name: "Figma", icon: IconFigma },
  { name: "Firebase", icon: IconFirebase },
  { name: "HTML", icon: IconHTML },
  { name: "Java", icon: IconJava },
  { name: "JavaScript", icon: IconJavaScript },
  { name: "JQuery", icon: IconJQuery },
  { name: "Kotlin", icon: IconKotlin },
  { name: "MongoDB", icon: IconMongoDB },
  { name: "MySQL", icon: IconMySQL },
  { name: "NextJS", icon: IconNextJS },
  { name: "NodeJS", icon: IconNodeJS },
  { name: "PHP", icon: IconPHP },
  { name: "PostgreSQL", icon: IconPostgreSQL },
  { name: "Python", icon: IconPython },
  { name: "React", icon: IconReact },
  { name: "ReactNative", alias: "react-native", icon: IconReactNative },
  { name: "Ruby", icon: IconRuby },
  { name: "Solidity", icon: IconSolidity },
  { name: "Swift", icon: IconSwift },
  { name: "Tailwind", icon: IconTailwind },
  { name: "TypeScript", icon: IconTypeScript },
  { name: "Vue", icon: IconVue },
];
