export const strategy_data = [
    {
        status: 'ENDING',
        underlying: 'TSLA',
        type: 'Long',
        strategyName: 'TSLA Sharp Spikes',
        winRate: '62%',
        avgTradeLength: '14 days',
        returnTTM: '32%',
        tradesTTM: 4,
    },
    {
        status: 'DAY 2',
        underlying: 'TSLA',
        type: 'Short',
        strategyName: 'TSLA Major Shifts',
        winRate: '77%',
        avgTradeLength: '9 days',
        returnTTM: '16%',
        tradesTTM: 5,
    },
    {
        status: 'STARTING',
        underlying: 'SPY',
        type: 'Short',
        strategyName: 'SPY Leading',
        winRate: '77%',
        avgTradeLength: '12 days',
        returnTTM: '18%',
        tradesTTM: 7,
    },
    {
        status: 'INACTIVE',
        underlying: 'SPY',
        type: 'Short',
        strategyName: 'SPY Leading',
        winRate: '77%',
        avgTradeLength: '12 days',
        returnTTM: '18%',
        tradesTTM: 7,
    },
    {
        status: 'INACTIVE',
        underlying: 'SPY',
        type: 'Short',
        strategyName: 'SPY Leading',
        winRate: '77%',
        avgTradeLength: '12 days',
        returnTTM: '18%',
        tradesTTM: 7,
    },
    {
        status: 'INACTIVE',
        underlying: 'SPY',
        type: 'Short',
        strategyName: 'SPY Leading',
        winRate: '77%',
        avgTradeLength: '12 days',
        returnTTM: '18%',
        tradesTTM: 7,
    },
];