import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HomeNavbar from '../(user)/_components/home-navbar'
import { cn } from '@codevs/ui'
import { UserWorkspaceContextProvider } from '../(user)/_components/user-workspace-context'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = createServerComponentClient({ cookies })

  const {
    data: { user },
  } = await supabase.auth.getUser()

  const { data, error } = await supabase
    .from('users')
    .select()
    .eq('id', user?.id)
    .single()

  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-slate-100')}>
        <UserWorkspaceContextProvider value={data}>
          <HomeNavbar />
          {children}
        </UserWorkspaceContextProvider>
      </body>
    </html>
  )
}
