import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Sidebar from "~/components/dashboard/Sidebar";
import { ToastProvider } from "@codevs/ui/toast";
import AdminVerify from "~/components/dashboard/AdminVerify";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "DineMate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="grid grid-cols-12 min-h-screen bg-[#F0F0F0]">
          <div className="col-span-3 xl:col-span-2 h-full bg-white ">
            <Sidebar />
          </div>
          <div className="col-span-9 xl:col-span-10 p-5">{children}</div>
          <AdminVerify />
          <ToastProvider />
        </div>        
      </body>
    </html>
  );
}
