export const todos = [
  {
    id: "1",
    title: "Complete Project A",
    subheader: "Finish before deadline",
    full_description: "Description for Project A",
    userTodoId: "user1",
    projectId: "project1",
    prio_level: "High",
    github_link: "https://github.com/projectA",
    created_at: "2024-03-28T12:00:00Z",
    updated_at: "2024-03-28T12:00:00Z",
    tagId: ["tag1", "tag2"],
    tags: [{ tag: "Tag1" }, { tag: "Tag2" }],
    userTodo: {},
    projects: {},
  },
  {
    id: "2",
    title: "Review Code for Feature B",
    subheader: "Review pull request",
    full_description: "Description for Feature B",
    userTodoId: "user2",
    projectId: "project2",
    prio_level: "Medium",
    github_link: "https://github.com/featureB",
    created_at: "2024-03-28T12:00:00Z",
    updated_at: "2024-03-28T12:00:00Z",
    tagId: ["tag2", "tag3"],
    tags: [{ tag: "Tag2" }, { tag: "Tag3" }],
    userTodo: {},
    projects: {},
  },
  {
    id: "3",
    title: "Write Documentation for Project C",
    subheader: "Complete API documentation",
    full_description: "Description for Project C",
    userTodoId: "user3",
    projectId: "project3",
    prio_level: "Medium",
    github_link: "https://github.com/projectC",
    created_at: "2024-04-01T12:00:00Z",
    updated_at: "2024-04-01T12:00:00Z",
    tagId: ["tag3", "tag4"],
    tags: [{ tag: "Tag3" }, { tag: "Tag4" }],
    userTodo: {},
    projects: {},
  },
  {
    id: "4",
    title: "Fix Bugs in Feature D",
    subheader: "Resolve all reported bugs",
    full_description: "Description for Feature D",
    userTodoId: "user4",
    projectId: "project4",
    prio_level: "Low",
    github_link: "https://github.com/featureD",
    created_at: "2024-04-02T12:00:00Z",
    updated_at: "2024-04-02T12:00:00Z",
    tagId: ["tag5", "tag6"],
    tags: [{ tag: "Tag5" }, { tag: "Tag6" }],
    userTodo: {},
    projects: {},
  },
  {
    id: "5",
    title: "Test Feature E",
    subheader: "Perform unit and integration tests",
    full_description: "Description for Feature E",
    userTodoId: "user5",
    projectId: "project5",
    prio_level: "High",
    github_link: "https://github.com/featureE",
    created_at: "2024-04-03T12:00:00Z",
    updated_at: "2024-04-03T12:00:00Z",
    tagId: ["tag7", "tag8"],
    tags: [{ tag: "Tag7" }, { tag: "Tag8" }],
    userTodo: {},
    projects: {},
  },
]
export const topnotchers = [
  {
    id: 1,
    ranking: 1,
    name: "Ryan",
    role: "FE",
    level: 1,
  },
  {
    id: 2,
    ranking: 2,
    name: "Jose",
    role: "FE",
    level: 1,
  },
  {
    id: 3,
    ranking: 3,
    name: "Zeff",
    role: "FE",
    level: 1,
  },
  {
    id: 4,
    ranking: 4,
    name: "Justine",
    role: "FE",
    level: 1,
  },
  {
    id: 5,
    ranking: 5,
    name: "Noel",
    role: "FE",
    level: 1,
  },
  {
    id: 6,
    ranking: 6,
    name: "Fritz",
    role: "FE",
    level: 1,
  },
  {
    id: 7,
    ranking: 7,
    name: "Prince",
    role: "FE",
    level: 1,
  },
  {
    id: 8,
    ranking: 8,
    name: "Catherine",
    role: "FE",
    level: 1,
  },
  {
    id: 9,
    ranking: 9,
    name: "David",
    role: "FE",
    level: 1,
  },
  {
    id: 10,
    ranking: 10,
    name: "Dominique",
    role: "FE",
    level: 1,
  },
]
