export const samplePosts = [
  {
    id: 1,
    user: "Ben Kelly",
    userImage: "/assets/images/bg-certificate.png",
    content:
      "This is hello world post. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    timestamp: "6h ago",
    images: ["/assets/images/bg-certificate.png"],
    reactions: { likes: 7, comments: 229 },
  },
  {
    id: 2,
    user: "Jane Smith",
    userImage: "/assets/images/bg-certificate.png",
    content: "Hello world! This is my first post.",
    timestamp: "5h ago",
    images: [
      "/assets/images/bg-certificate.png",
      "/assets/images/bg-certificate.png",
    ],
    reactions: { likes: 15, comments: 10 },
  },
  {
    id: 3,
    user: "Alice Johnson",
    userImage: "/assets/images/bg-certificate.png",
    content: "Loving this platform!",
    timestamp: "1d ago",
    images: [
      "/assets/images/bg-certificate.png",
      "/assets/images/bg-certificate.png",
      "/assets/images/bg-certificate.png",
    ],
    reactions: { likes: 20, comments: 5 },
  },
  {
    id: 4,
    user: "John Doe",
    userImage: "/assets/images/bg-certificate.png",
    content: "Check out these amazing photos!",
    timestamp: "2d ago",
    images: [
      "/assets/images/bg-certificate.png",
      "/assets/images/bg-certificate.png",
      "/assets/images/bg-certificate.png",
      "/assets/images/bg-certificate.png",
    ],
    reactions: { likes: 50, comments: 30 },
  },
  {
    id: 5,
    user: "Emily Davis",
    userImage: "/assets/images/bg-certificate.png",
    content: "What a beautiful day!",
    timestamp: "3d ago",
    images: [],
    reactions: { likes: 10, comments: 2 },
  },
  {
    id: 6,
    user: "Michael Brown",
    userImage: "/assets/images/bg-certificate.png",
    content: "Just finished a great book!",
    timestamp: "4d ago",
    images: ["/assets/images/bg-certificate.png"],
    reactions: { likes: 25, comments: 8 },
  },
  {
    id: 7,
    user: "Sarah Wilson",
    userImage: "/assets/images/bg-certificate.png",
    content: "Excited for the weekend!",
    timestamp: "5d ago",
    images: [],
    reactions: { likes: 30, comments: 12 },
  },
  {
    id: 8,
    user: "Chris Johnson",
    userImage: "/assets/images/bg-certificate.png",
    content: "Throwback to my vacation!",
    timestamp: "6d ago",
    images: [
      "/assets/images/bg-certificate.png",
      "/assets/images/bg-certificate.png",
    ],
    reactions: { likes: 40, comments: 20 },
  },
  {
    id: 9,
    user: "Anna Lee",
    userImage: "/assets/images/bg-certificate.png",
    content: "Feeling grateful today.",
    timestamp: "1w ago",
    images: [],
    reactions: { likes: 18, comments: 4 },
  },
  {
    id: 10,
    user: "David Clark",
    userImage: "/assets/images/bg-certificate.png",
    content: "Check out my latest project!",
    timestamp: "2w ago",
    images: ["/assets/images/bg-certificate.png"],
    reactions: { likes: 60, comments: 25 },
  },
];
