export const samplePosts = [
  {
    id: 1,
    user: "Ben Kelly",
    userImage: "/assets/images/bg-certificate.png",
    content:
      "This is hello world post. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    timestamp: "4h ago",
    image: "/assets/images/bg-certificate.png",
    reactions: { likes: 7 },
    postUrl: "https://example.com/posts/1",
  },
  {
    id: 2,
    user: "Jane Smith",
    userImage: "/assets/images/bg-certificate.png",
    content: "Hello world! This is my first post.",
    timestamp: "5h ago",
    image: "/assets/images/bg-certificate.png",
    reactions: { likes: 15 },
    postUrl: "https://example.com/posts/2",
  },
  {
    id: 3,
    user: "Alice Johnson",
    userImage: "/assets/images/bg-certificate.png",
    content: "Loving this platform!",
    timestamp: "1d ago",
    image: "/assets/images/bg-certificate.png",
    reactions: { likes: 20 },
    postUrl: "https://example.com/posts/3",
  },
  {
    id: 4,
    user: "John Doe",
    userImage: "/assets/images/bg-certificate.png",
    content: "Check out these amazing photos!",
    timestamp: "2d ago",
    image: "/assets/images/bg-certificate.png",
    reactions: { likes: 50 },
    postUrl: "https://example.com/posts/4",
  },
  {
    id: 5,
    user: "Emily Davis",
    userImage: "/assets/images/bg-certificate.png",
    content: "What a beautiful day!",
    timestamp: "3d ago",
    image: "/assets/images/bg-certificate.png",
    reactions: { likes: 10 },
    postUrl: "https://example.com/posts/5",
  },
];
