name: CI for Monorepo with Turbo and Changed Files Detection

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  turbo:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_PRODUCT_NAME: "ClapUp"
      NEXT_PUBLIC_SITE_TITLE: "Clapper Digital Business Card"
      NEXT_PUBLIC_SITE_DESCRIPTION: "App"
      NEXT_PUBLIC_SITE_URL: "https://localhost:3000"
      NEXT_PUBLIC_DEFAULT_LOCALE: "en"
      NEXT_PUBLIC_DEFAULT_THEME_MODE: "light"
      NEXT_PUBLIC_THEME_COLOR: "#22C55E"
      NEXT_PUBLIC_THEME_COLOR_DARK: "#1e1e1e"
      NEXT_PUBLIC_SUPABASE_URL: "supabaseurl"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "supabaseanonkey"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Cache node_modules and Turbo output
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .turbo
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Build changed packages
        run: pnpm dlx turbo@latest run build --filter=...[origin/dev]

      # Uncomment when ready for tests
      # - name: Run tests for changed packages
      #   run: pnpm dlx turbo@latest run test --filter=...[origin/dev]

      # Trigger Vercel deployment using deploy hook
      - name: Deploy to Vercel
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_9kHRoASFcMABb4SuIcPINlnyH3tR/2azM3yQP4t"
