name: CI for Monorepo with Turbo and Changed Files Detection

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  turbo:
    runs-on: ubuntu-latest

    env:
      # Non-sensitive environment variables
      NEXT_PUBLIC_SITE_TITLE: "Codebility"
      NEXT_PUBLIC_DEFAULT_LOCALE: "en"
      NEXT_PUBLIC_DEFAULT_THEME_MODE: "system"
      NEXT_PUBLIC_THEME_COLOR: "purple"
      NEXT_PUBLIC_THEME_COLOR_DARK: "black"
      NEXT_PUBLIC_APP_BASE_URL: "http://localhost:3000"
      
      # Sensitive variables from repository secrets
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_FOUNDER_USER_ID: ${{ secrets.NEXT_PUBLIC_FOUNDER_USER_ID }}
      NEXT_PUBLIC_RESEND_API_KEY: ${{ secrets.NEXT_PUBLIC_RESEND_API_KEY }}
      NEXT_PUBLIC_MESSENGER_WAITLIST: ${{ secrets.NEXT_PUBLIC_MESSENGER_WAITLIST }}
      NEXT_PUBLIC_DISCORD_LINK: ${{ secrets.NEXT_PUBLIC_DISCORD_LINK }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      DB_SERVICE_ROLE: ${{ secrets.DB_SERVICE_ROLE }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Cache Turbo output
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Build changed packages comment out if packages are properly fixed
      #   run: pnpm dlx turbo@latest run build --filter=...[HEAD~1]

      # - name: Run linting for changed packages comment out if packages are properly fixed
      #   run: pnpm dlx turbo@latest run lint --filter=...[HEAD~1]

      - name: Build Codebility
        run: pnpm run codebility:build

      # Uncomment when ready for tests
      # - name: Run tests for changed packages
      #   run: pnpm dlx turbo@latest run test --filter=...[HEAD~1]

      # Trigger Vercel deployment using deploy hook
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"