name: Deploy Discord Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allow manual run

jobs:
  deploy-bot:
    name: Deploy Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install bot dependencies
        run: |
          cd apps/codebility/app/bot
          pnpm install

      - name: Start Discord bot
        run: |
          cd apps/codebility/app/bot
          pnpm run start
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NODE_ENV: production
